[build]
  publish = "public"  # Directory where your static files are located
  functions = "netlify/functions"  # Directory for Netlify functions

[dev]
  functions = "netlify/functions"  # Directory for Netlify functions during local development