[build]
  publish = "public" # Replace with your build output directory
  functions = "/Users/oliverdeighton/Documents/GitHub/MrMoney0123.github.io/netlify-functions/" # Replace with your functions directory

[dev]
  functions = "/Users/oliverdeighton/Documents/GitHub/MrMoney0123.github.io/netlify-functions/"